<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if (defined('MW_INSTALL_PATH')) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname(__FILE__);
}

$version = phpversion();
if (preg_match("@5.3@", $version)) {
	$path = array($IP, "$IP/includes", "$IP/languages", "$IP/extensions/wikihow", '/usr/local/lib/php/openid-php-openid-782224d');
} else {
	$path = array($IP, "$IP/includes", "$IP/languages", "$IP/extensions/wikihow", '/usr/local/lib/php/php-openid-2.1.0');
}
set_include_path( implode(PATH_SEPARATOR, $path) . PATH_SEPARATOR . get_include_path() );

require_once("$IP/includes/DefaultSettings.php");

# Include site revision if it exists, so that URLs get updated on changes
@include_once("$IP/siterev.php");
if (!defined('WH_SITEREV')) define('WH_SITEREV', '100');

define('IS_PROD_EN_SITE', true);
require_once("$IP/LocalKeys.php");

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ($wgCommandLineMode) {
	if ( isset($_SERVER) && array_key_exists('REQUEST_METHOD', $_SERVER) ) {
		die("This script must be run from the command line\n");
	}
} elseif ( empty($wgNoOutputBuffer) ) {
	## Compress output if the browser supports it
	if( !ini_get('zlib.output_compression') ) @ob_start('ob_gzhandler');
}

$wgSitename = 'wikiHow';
$wgCookieDomain = 'wikihow.com';
$isDevServer = strpos(@$_SERVER['SERVER_NAME'], 'wikidiy.com') !== false;
if (@$_SERVER['SERVER_NAME'] == 'm.wikihow.com' ||
	@$_SERVER['SERVER_NAME'] == 'carrot.wikihow.com' ||
	@$_SERVER['SERVER_NAME'] == 'testers.wikihow.com' ||
	@$_SERVER['SERVER_NAME'] == 'html5.wikihow.com' ||
	@$_SERVER['SERVER_NAME'] == 'spare1.wikihow.com' ||
	//strpos(@$_SERVER['SERVER_NAME'], 'apache') === 0 ||
	//strpos(@$_SERVER['SERVER_NAME'], 'squid') === 0 ||
	//@$_SERVER['SERVER_PORT'] == 8000 ||
	$isDevServer)
{
	$portStr = (!empty($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] != '80' ? ':' . $_SERVER['SERVER_PORT'] : '');
	$wgServer = 'http://' . $_SERVER['SERVER_NAME'] . $portStr;
	if ($isDevServer) $wgCookieDomain = 'wikidiy.com';
} else {
	$wgServer = 'http://www.wikihow.com';
}

$wgLogo = '/skins/WikiHow/wikiHow.gif';

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath = '';
$wgArticlePath = "$wgScriptPath/$1";

## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail = true;
$wgEnableUserEmail = true;

$wgEmergencyContact = 'wiki@wikihow.com';
$wgPasswordSender = 'wikiHow <wiki@wikihow.com>';

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = true;
$wgEmailAuthentication = true;

$wgDBservers = array(
	array(
		'host'     => WH_DATABASE_MASTER,
		'dbname'   => WH_DATABASE_NAME,
		'user'     => WH_DATABASE_USER,
		'password' => WH_DATABASE_PASSWORD,
		'load'     => 1
	),
);
if (defined('WH_DATABASE_SLAVE1')) {
	$wgDBservers[] = array(
		'host'     => WH_DATABASE_SLAVE1,
		'dbname'   => WH_DATABASE_NAME,
		'user'     => WH_DATABASE_USER,
		'password' => WH_DATABASE_PASSWORD,
		'load'     => 1
	);
}

# Schemas for Postgres
$wgDBmwschema = 'mediawiki';
$wgDBts2schema = 'public';

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = array(
	WH_MEMCACHED_SERVER_1,
);
if (defined('WH_MEMCACHED_SERVER_2')) $wgMemCachedServers[] = WH_MEMCACHED_SERVER_2;

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX = false;

$wgLocalInterwiki = $wgSitename;

$wgLanguageCode = 'en';
$wgProxyKey = WH_PROXY_KEY;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'wikihowskin';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ''; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = '';
$wgRightsText = '';
$wgRightsIcon = '';
#$wgRightsCode = ''; # Not yet used

$wgDiff3 = '/usr/bin/diff3';

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate('YmdHis', @filemtime(__FILE__));
$wgCacheEpoch = max($wgCacheEpoch, $configdate);
#$wgReadOnly = "<br/><br/><b><font color=red size='+1'>We are currently doing some maintenance, should be back up and running by 12am EST, sorry for the inconvenience.</font>";


$wgHooks = array();

$wgUseSquid = true;
$wgSquidServers = array(WH_SQUID1);
if (defined('WH_SQUID2')) $wgSquidServers[] = WH_SQUID2;
$wgSquidMaxage = 6 * 60 * 60; # 6 hours

#require_once("$IP/extensions/kaltura_wiki_ext/kaltura_extension.php");
# QUARANTINE
require_once("$IP/extensions/wikihow/DailyStats.php");
require_once("$IP/extensions/wikihow/Misc.php");
require_once("$IP/extensions/wikihow/Importvideo.php");

#require_once("$IP/extensions/wikihow/Blank.php");

require_once("$IP/extensions/CheckUser/CheckUser.php");
require_once("$IP/extensions/Newuserlog/Newuserlog.php");
require_once("$IP/extensions/SpamBlacklist/SpamBlacklist.php");

$wgSpamBlacklistFiles = array(
	"DB: " . WH_DATABASE_NAME . " Spam-Blacklist",
	"$IP/extensions/SpamBlacklist/wikimedia_blacklist",
	"$IP/extensions/SpamBlacklist/wikihow_custom",
);
require_once("$IP/extensions/Cite/Cite.php");
require_once("$IP/extensions/AntiSpoof/AntiSpoof.php");
require_once("$IP/extensions/UniversalEditButton/UniversalEditButton.php");
require_once("$IP/extensions/Drafts/Drafts.php");
require_once("$IP/extensions/ImageMap/ImageMap.php");

#
# WIKIHOW Extensions
#

require_once("$IP/includes/EasyTemplate.php");
require_once("$IP/extensions/wikihow/Articlestats.php");
require_once("$IP/extensions/wikihow/Patrolcount.php");
require_once("$IP/extensions/BlockTitles/BlockTitles.php");
require_once("$IP/extensions/wikihow/Video.php");
require_once("$IP/extensions/wikihow/SpecialLSearch.php");
require_once("$IP/extensions/wikihow/SpecialGoogSearch.php");
require_once("$IP/extensions/wikihow/SpecialNVGadget.php");
require_once("$IP/extensions/wikihow/SpecialGoogGadget.php");
require_once("$IP/extensions/wikihow/SpecialNewcontributors.php");
require_once("$IP/extensions/wikihow/SpecialTitleSearch.php");
require_once("$IP/extensions/wikihow/SpecialThankAuthors.php");
require_once("$IP/extensions/wikihow/CreatePage.php");
require_once("$IP/extensions/wikihow/Feed.php");
require_once("$IP/extensions/wikihow/Follow.php");
require_once("$IP/extensions/wikihow/Standings.php");
require_once("$IP/extensions/wikihow/QC.php");
require_once("$IP/extensions/wikihow/CheckG.php" );
require_once("$IP/extensions/wikihow/Vanilla.php");
require_once("$IP/extensions/ProxyConnect/ProxyConnect.php");
require_once("$IP/extensions/wikihow/AddRelatedLinks.php");
require_once("$IP/extensions/wikihow/ImportXML.php");
require_once("$IP/extensions/wikihow/TopCategoryHooks.php");
require_once("$IP/extensions/wikihow/Netseer.php" );
require_once("$IP/extensions/wikihow/Managepagelist.php" );
require_once("$IP/extensions/wikihow/Unpatrol.php" );
require_once("$IP/extensions/wikihow/RCPatrol.php");
require_once("$IP/extensions/wikihow/FBConnect.php");
require_once("$IP/extensions/wikihow/Categorylisting.php");
require_once("$IP/extensions/wikihow/FixCaps.php");
require_once("$IP/extensions/wikihow/Randomizer.php");
require_once("$IP/extensions/wikihow/Radlinks.php");
require_once("$IP/extensions/wikihow/RCBuddy.php");
require_once("$IP/extensions/wikihow/BuildWikiHow.php");
require_once("$IP/extensions/wikihow/SpecialGeneratefeed.php");
require_once("$IP/extensions/wikihow/ToolbarHelper.php");
require_once("$IP/extensions/wikihow/GoogleAPIResults.php");
require_once("$IP/extensions/wikihow/SpecialSitemap.php");
require_once("$IP/extensions/wikihow/SpecialEmailLink.php");
require_once("$IP/extensions/wikihow/Newarticleboost.php");
require_once("$IP/extensions/wikihow/Suggest.php");
require_once("$IP/extensions/wikihow/MWMessages.php");
require_once("$IP/extensions/wikihow/RateArticle.php");
#require_once("$IP/extensions/wikihow/SpamDiffTool.php");
require_once("$IP/extensions/wikihow/Bunchpatrol.php");
require_once("$IP/extensions/wikihow/Republish.php");
require_once("$IP/extensions/wikihow/MultipleUpload.php");
require_once("$IP/extensions/wikihow/SpecialGenerateJSFeed.php");
require_once("$IP/extensions/FormatEmail/FormatEmail.php");
require_once("$IP/extensions/wikihow/MagicArticlesStarted.php");
require_once("$IP/extensions/Postcomment/SpecialPostcomment.php");
require_once("$IP/extensions/Renameuser/SpecialRenameuser.php");
require_once("$IP/extensions/wikihow/FacebookPage.php");
require_once("$IP/extensions/wikihow/Categoryhelper.php");
require_once("$IP/extensions/wikihow/CheckJS.php");
require_once("$IP/extensions/wikihow/Sugg.php");
require_once("$IP/extensions/wikihow/RelatedArticle.php");
require_once("$IP/extensions/wikihow/Monitorpages.php");
require_once("$IP/extensions/wikihow/Changerealname.php");
require_once("$IP/extensions/ConfirmEdit/ConfirmEdit.php");
require_once("$IP/extensions/ConfirmEdit/FancyCaptcha.php");
require_once("$IP/extensions/ParserFunctions/ParserFunctions.php");
require_once("$IP/extensions/wikihow/AutotimestampTemplates.php");
require_once("$IP/extensions/ImportFreeImages/ImportFreeImages.php");
require_once("$IP/extensions/PopBox/PopBox.php");
require_once("$IP/extensions/wikihow/EmbedVideo.php");
require_once("$IP/extensions/wikihow/Mypages.php");
require_once("$IP/extensions/wikihow/WikiHowHooks.php");
require_once("$IP/extensions/wikihow/MarkFeatured.php");
require_once("$IP/extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");
require_once("$IP/extensions/wikihow/UserTalkTool.php");
require_once("$IP/extensions/wikihow/RCWidget.php");
require_once("$IP/extensions/wikihow/Welcome.php");
require_once("$IP/extensions/wikihow/Authorleaderboard.php");
require_once("$IP/extensions/wikihow/AuthorEmailNotification.php");
require_once("$IP/extensions/wikihow/Charityleaderboard.php");
require_once("$IP/extensions/wikihow/Avatar.php");
require_once("$IP/extensions/wikihow/ProfileBox.php");
require_once("$IP/extensions/wikihow/QuickNoteEdit.php");
require_once("$IP/extensions/wikihow/eiu/Easyimageupload.php");
require_once("$IP/extensions/wikihow/Leaderboard.php");
require_once("$IP/extensions/wikihow/mobile/MobileWikihow.php");
require_once("$IP/extensions/wikihow/FeaturedContributor.php");
require_once("$IP/extensions/wikihow/IntroImageAdder.php");
require_once("$IP/extensions/OpenID/OpenID.setup.php");
require_once("$IP/extensions/wikihow/FollowWidget.php");
require_once("$IP/extensions/wikihow/Videoadder.php");
require_once("$IP/extensions/wikihow/WikiHow_i18n.class.php");
require_once("$IP/extensions/wikihow/WikihowCSSDisplay.php");
require_once("$IP/extensions/wikihow/StatsList.php");
require_once("$IP/extensions/wikihow/AdminResetPassword.php");
require_once("$IP/extensions/wikihow/AdminRemoveAvatar.php");
require_once("$IP/extensions/wikihow/Bloggers.php");
require_once("$IP/extensions/wikihow/LoginReminder.php");
require_once("$IP/extensions/wikihow/NewHowtoArticles.php");
require_once("$IP/extensions/wikihow/editfinder/EditFinder.php");
require_once("$IP/extensions/wikihow/h5e/Html5editor.php");
require_once("$IP/extensions/wikihow/ctalinks/CTALinks.php");
require_once("$IP/extensions/wikihow/thumbsup/ThumbsUp.php");
require_once("$IP/extensions/wikihow/dashboard/CommunityDashboard.php");
require_once("$IP/extensions/wikihow/dashboard/AdminCommunityDashboard.php");
require_once("$IP/extensions/wikihow/IheartwikiHow.php");

$wgOpenIDServerStoreType = 'memcached';
$wgOpenIDConsumerStoreType = 'memcached';

# This needs to be redesigned
# POSSIBLY REMOVING THIS

$wgBlockOpenProxies = true;
$wgProxyScriptPath = "$IP/includes/proxy_check.php";
$wgProxyDefaultBlockLength = '3 month';

# TODO: move this to WikiHowHooks.php
$wgHooks['ArticleSaveComplete'][] = array('wfArticleSaveComplete', $data);
$wgHooks['TitleMoveComplete'][] = array('wfTitleMoveComplete', $data);
$wgHooks['ArticleDelete'][] = array('wfArticleDelete', $data);

$wgAntiLockFlags = ALF_NO_LINK_LOCK | ALF_NO_BLOCK_LOCK;
$wgJobRunRate = 0; # see php maintenance/runJobs.php

$wgSessionsInMemcached = true;

#$wgExternalDiffEngine = 'wikidiff2';
$wgRateLimits['mailpassword'] = array('ip' => array(3, 3600));
$wgForumLink = 'http://forums.wikihow.com/';
$wgCompressRevisions  = true;
$wgAllowExternalImages = false;

$wgShowEditSectionLink = true;

$wgSharedDB = WH_DATABASE_NAME_SHARED;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageResize = true;

$wgShowSQLErrors = true;

# DEBUGGING
#$wgDebugLogFile = '/tmp/wiki112-debug.log';
#$wgProfileLimit = 2.0;
#$wgProfileCallTree = true;

$wgShowExceptionDetails = true;
$wgUseCategoryBrowser = true;

# Tidy
$wgUseTidy = true;
$wgAlwaysUseTidy = false;
$wgTidyOpts = '--show-body-only yes';
$wgTidyBin = '/usr/local/bin/tidy';
#$wgTidyConf = $IP.'/extensions/tidy/tidy.conf';

## See list of skins and their symbolic names in languages/Language.php
$wgExternalDiffEngine = 'wikidiff2';
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = '/usr/local/bin/convert';
$wgUploadSizeWarning = 10485760; # 10mb

$wgLocaltimezone = 'GMT';
$wgRSSOffsetHours = 8;

#$wgAllowCopyUploads = true;
$wgEnableAPI = true;
$wgGoogleAPIKey = WH_GOOGLE_API_KEY;
$wgAllowDisplayTitle = true;

$wgMinimalPasswordLength = 4;
$wgUseLucene = true;
$wgFileExtensions = array('png', 'gif', 'jpg', 'jpeg', 'pdf');
$wgSVGConverter = 'rsvg';

# Google Mini
$wgUseGoogleMini = true;
$wgGoogleMiniHost = array(
	array(1, 'http://' . WH_GOOGLE_MINI_HOST),
);
$wgCacheGoogleMiniResults = true;

$wgGroupPermissions['user']['patrol'] = true;
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['user']['rollback'] = true;
$wgGroupPermissions['sysop']['move'] = true;

$wgCaptchaTriggers['addurl'] = true;
$wgGroupPermissions['user']['skipcaptcha'] = true;

$wgShowHostnames = true;

define('KALTURA_NAMESPACE_STRING', 'Kaltura');
define('KALTURA_NAMESPACE_ID', 320);
define('KALTURA_DISCUSSION_NAMESPACE_ID', 321);
$wgExtraNamespaces[KALTURA_NAMESPACE_ID] = KALTURA_NAMESPACE_STRING ;
$wgExtraNamespaces[KALTURA_NAMESPACE_ID + 1] = KALTURA_NAMESPACE_STRING . '_Talk';

$wgDraftsLifeSpan = 365;
$egDraftsLifeSpan = $wgDraftsLifeSpan; # tmp

$wgFavicon = 'http://pad1.whstatic.com/favicon.ico';
$wgUseAjax = true;
$wgRCMaxAge = 7776000; # 90 days

# We needed to raise this limit (default MediaWiki limit is about 100k) because
# it was cause the ImageMagick convert to fail on some hosts (ulimit is
# applied to the convert command).
$wgMaxShellFileSize = 2*1024*1024; # 2 mb
$wgMaxShellMemory = 2*1024*1024; # 2 mb

$wgWikiHowSections = array('ingredients', 'steps', 'video', 'tips', 'warnings', 'relatedwikihows', 'thingsyoullneed', 'sources');

# Facebook connect settings
$wgFBConnectAPIkey = WH_FACEBOOK_CONNECT_API_KEY;
$wgFBConnectSecret = WH_FACEBOOK_CONNECT_SECRET;

# Legacy for old article requests
define('NS_ARTICLE_REQUEST', 16);
define('NS_ARTICLE_REQUEST_TALK', 17);
$wgExtraNamespaces[NS_ARTICLE_REQUEST] = 'Request';
$wgExtraNamespaces[NS_ARTICLE_REQUEST_TALK] = 'Request_talk';

$wgGoogleAjaxKey = WH_GOOGLE_AJAX_SEARCH_API_KEY;
$wgGoogleAjaxSig = WH_GOOGLE_AJAX_SEARCH_SIG;

$wgIgnoreNamespacesForEditCount = array(2, 3, 18);

$wgEnableLateLoadingAds = true;

$wgAvailableRights[] = 'staff';
$wgGroupPermissions['staff'] = $wgGroupPermissions['sysop'];
$wgGroupPermissions['staff' ]['newbienap']   = true;
$wgGroupPermissions['staff' ]['importxml']   = true;
$wgGroupPermissions['staff' ]['qc']   = true;

$wgVanillaDB = array(
           'host'      => WH_VANILLA_HOST,
           "dbname"    => WH_VANILLA_DBNAME,
           "user"      => WH_VANILLA_USER,
           "password"  => WH_VANILLA_PASSWORD
		);

$wgMaxSquidPurgeTitles = 50;
$wgUpdateRowsPerJob = 1; 

date_default_timezone_set("UTC");

