<?
class CheckMarks {
	static $stepsMsgs = array(
		"Another step bites the dust.",
		"Crossing things off lists feels good, doesn't it?",
		"Do it again!",
		"Don't stop now, you are on a roll.",
		"Getting close...",
		"Getting closer...",
		"Getting there!",
		"Go you!",
		"Good job. ",
		"Great!",
		"He (or she) shoots, he (or she) scores!",
		"Hurry. Another step awaits!",
		"I can't imagine anyone doing this better.",
		"I feel a completed task in your future.",
		"I forsee many completed steps in your future.",
		"I like the way you check.",
		"I've never seen a better completion of a step.",
		"Keep going!",
		"Keep it up!",
		"Keep on checkin!",
		"Keep on keepin' on!",
		"Keep up the good work.",
		"Movin' right along.",
		"Nailed it!",
		"Nice going!",
		"Nice job!",
		"Nothing succeeds like success.",
		"Now you're cooking!",
		"Oh yeah!",
		"One less thing to do today.",
		"One step closer...",
		"Ready for the next step!",
		"Rock on.",
		"Score.",
		"Hopefully that was easy.",
		"Showing how it's done!",
		"Slow down, you are making the rest of us slackers look bad.",
		"Step by step, you'll make it.",
		"Success.",
		"That step never stood a chance.",
		"That's the sweet smell of progress.",
		"The end is in sight.",
		"Way to stay focused!",
		"I'm very impressed with your progress.",
		"Wasn't that fun?",
		"Woot!",
		"Wow,  nice work!",
		"Wow, that was impressive!",
		"Wow. That was awesome.",
		"Wowsas!",
		"Yippee-kay-yay!",
		"You can do it!",
		"You got this.",
		"You owned that step.",
		"You rock!",
		"You are doing a great job.",
		"You'll get through this in no time.",
		"You're fast!",
		"You're on your way!",
		"Yowza!",
		"I like.",
		"Nice.",
		"Congratulations! ",
		"Congraulations. Can't wait for you to check another! :)",
		"Easy, right? ",
		"Good form!",
		"wikiHow to do it!",
	);

	static $lastStepMsgs = array(
		"Annnnd.... that's a wrap. Good job!",
		"Nice. Now are you ready for another?",
		"Awesome work!",
		"Awesome! You're done.",
		"Good job. Completed with flair and gusto.",
		"Congrats!",
		"Congratulations! You made it to the end.",
		"Couldn't have done it better ourselves.",
		"Fantastic!",
		"Finished! Congrats.",
		"Give yourself a pat on the back!",
		"Congrats. Go forth and show off.",
		"Good job completing this how-to.",
		"You are done. High five!",
		"You are done. Hip, hip, hooray!",
		"How to = DONE.",
		"How to? Not anymore. Now you have know how.",
		"I think you've earned some bragging rights.",
		"Done. And just like a rockstar!",
		"Done. Accomplishment feels good.",
		"Not everyone can how to like you do.  Nice work!",
		"You did it! Tell all your friends. ",
		"Yay, you're done!",
		"Success!",
		"Success! Now that deserves a fist bump.",
		"That's how it's done!",
		"That's it... You're done!",
		"We hereby grant you the title of How to master.",
		"We hope you enjoyed the article!",
		"Congrats. wikiDone well.",
		"wikiDone. Great job.",
		"wikiHow-WOW!",
		"Done. With this new knowledge you will be the envy of your friends.",
		"We knew you could do it. Congrats.",
		"You did it. Great job.",
		"You made that look easy.",
		"You really know how to how to.",
		"You rocked this wikiHow.",
		"You showed that task who's boss!",
		"Success. Good work.",
		"Good job.",
		"You are done. We're very proud of you.",
		"Congratulations! Job well done.",
	);
	
	static $titles = array(
		"Know if You're in Love",
		"Know if a Guy Likes You",
		"Know if You Have a Crush on a Guy",
		"Clean Your Room",
		"Get a Boyfriend",
		"Show a Guy That You Like Him",
		"Make a Guy Like You (Pre Teens)",
		"Get a Girl to Like You",
		"Look Pretty",
		"Get a Guy to Notice You",
		"Know if a Girl Likes You",
		"Get over a Crush",
		"Get a Girl to Like You in Middle School",
		"Get a Guy to Like You",
		"Look Attractive (Guys)",
		"Get a Boy in Middle School to Like You",
		"Make a New Facebook Account",
		"Talk to a Guy You Like",
		"Tell if a Girl Likes You in School",
		"Fall Asleep",
		"Cure a Stomach Ache",
		"Ask a Girl to Prom in a Cute Way",
		"French Kiss",
		"Get Six Pack Abs",
		"Get a Girlfriend in Middle School",
		"Get Your Ex Boyfriend Back",
		"Get Rid of a Sore Throat",
		"Kiss",
		"Get a Guy Who Has a Girlfriend",
		"Get a Boy to Kiss You when You're Not Dating Him",
		"Ask a Girl Out",
		"Have a First Kiss",
		"Make Your Hair Grow Faster",
		"Kiss a Girl",
		"Permanently Delete a Facebook Account",
		"Make Your Boyfriend Kiss You",
		"Fall Asleep Easier As a Teen",
		"Impress a Girl",
		"Be a Good Boyfriend As a Teen",
		"Tell a Girl You Like Her",
		"Lucid Dream",
		"Tell if a Girl Is Flirting With You",
		"Be Popular",
		"Do Simple and Cute Hairstyles",
		"Earn Money (for Kids)",
		"Get a Guy That Likes You to Ask You Out",
		"Kiss a Boy",
		"Make a Girl Feel Special",
		"Touch a Girl",
		"Lose Weight Fast",
		"Run Away From Home",
		"Hypnotize Someone",
		"Make Your Girlfriend Happy",
		"Treat a Bee Sting",
		"Be a Good Girlfriend in Middle School",
		"Attract a Boy in the Fifth Grade",
		"Flirt with a Guy",
		"Write a Song",
		"Fishtail Braid",
		"Get Your Best Friend Back",
		"Act Around a Guy You Like",
		"Fake Sick to Stay Home from School",
		"Fold a Dollar Into a Heart",
		"Get a Flat Stomach",
		"Make French Toast",
		"Clean Your Room Fast",
		"Win a Girl's Heart",
		"Stop a Masturbation Addiction",
		"Treat an Infected Ear Piercing",
		"Look Pretty with No Makeup As a Preteen",
		"Be Confident",
		"Lose Your Virginity Without Pain (Girls)",
		"Be the Prettiest Girl in School",
		"Make School Time Fly",
		"Ask a Guy Out",
		"Clear a Stuffy Nose",
		"Get Ready for Bed",
		"Build Self Confidence",
		"Become Flexible",
		"Fold a Note Into a Heart",
		"Impress a Guy",
		"Get Over a Break Up",
		"Get a Boyfriend in Middle School",
		"Make Friends",
		"Host a Sleepover",
		"Show Your Love to Your Boyfriend",
		"Pierce Your Own Nose",
		"Fall Asleep Fast",
		"Physically Flirt with a Girl",
		"Make a Duct Tape Wallet",
		"Speak in a British Accent",
		"Persuade Your Parents to Get a Dog",
		"Read Palms",
		"Get Ready for Prom in Advance",
		"Have Fun Alone",
		"Crack Your Back",
		"Look and Act Like Cat Valentine from Victorious",
		"Get Rid of Blackheads (Various Methods)",
		"Make Out",
		"Ask a Guy out Even Though You're Scared to Death",
		"Attract the Guy You Have a Crush On",
		"Get Rich Quick if You're a Kid",
		"Solve a Rubik's Cube (Easy Move Notation)",
		"Make Out for the First Time",
		"Treat a Burn",
		"Be Positive",
		"Show Your Boyfriend That You Love Him and Only Him",
		"Be Girly",
		"Stop Cutting Yourself",
		"Get Noticed by Your Crush",
		"Study for a Test",
		"Cure a Child's Stomach Ache",
		"Be a Tomboy",
		"Get a Girl to Like You in 7th Grade",
		"Make a Girl Become Obsessed with You",
		"Get Your Ex Girlfriend Back",
		"Get a Girl to Fall in Love with You",
		"Make Your Teacher Have a Crush on You",
		"Be a Good Boyfriend",
		"Be a Girly Girl",
		"Straighten Your Hair",
		"Stop Yourself from Crying",
		"Tell when a Girl Is Interested in You",
		"Get Rid of Black Circles Under Your Eyes",
		"Know If You Are a Lesbian",
		"Kiss a Boy for the First Time",
		"Get Over Your First Love",
		"Make a Relationship Work",
		"Make a Boy Like You in Middle School",
		"French Braid",
		"Hint to a Boy That You Like Him",
		"Clear Your Browser's Cookies",
		"Get a Girlfriend",
		"Make Out With a Girl",
		"Be a Perfect Girl",
		"Make Yourself Tired So That You'll Fall Asleep",
		"Flirt",
		"Get Ready for School (for Girls)",
		"Win a Teenage Girl's Heart",
		"Stay Up All Night Alone (for Kids)",
		"Flirt Through Text Messages",
		"Impress a Girl and Make Her Fall in Love with a Boy",
		"Be a Good Girlfriend",
		"Lose Belly Fat",
		"Pierce Your Own Belly Button at Home",
		"Know if You Are Gay",
		"See if He's the One",
		"Cure Numbness in Your Feet & Toes",
		"Fold an Origami Star (Shuriken)",
		"Deal With Your Period",
		"Tell if You Genuinely Like Someone",
		"Get Rid of Brown Spots Using Home Remedies",
		"Know if a Girl Doesn't Like You Back",
		"Touch a Guy",
		"Tell if He Really Loves You",
		"Get the Boy You Like to Go from Total Stranger, to Friend, to Boyfriend",
		"Give Signs to Your Crush You Like Him",
		"Ask a Boy out in Middle School",
		"Prepare an Emergency School Kit for Girls",
		"Give Someone a Hickey",
		"Talk to a Girl You Like for the First Time",
		"Tell a Girl You Love Her when You Are Not Sure She Loves You Back",
		"Be a Normal Good Looking Girl from Inside and Outside",
		"Keep a Boyfriend",
		"Seduce a Woman",
		"Win Your Crush (Girls)",
		"Fold a Paper Rose",
		"Be a Ninja",
		"Look Sexy",
		"Act Around Girls",
		"Get Rid of Warts",
		"Hold Hands",
		"Know for Sure if a Boy Likes You Before You Ask Him Out",
		"Make Any Girl Want to Kiss You",
		"Make Jacob's Ladder out of String",
		"Stop Liking Your Crush",
		"Write a Rap Song",
		"Be Emo",
		"Act Like a Tomboy",
		"Get Beautiful, Glowing Skin",
		"Make a Long Distance Relationship Work",
		"Apply Eyeliner",
		"Get a Girl to Be Your Girlfriend",
		"Socialize, Be Funny and Make Friends",
		"Annoy Your Siblings",
		"Make Your Girlfriend Like You More",
		"Survive Middle School",
		"Be a Scene Kid",
		"Be Cool and Popular in Sixth Grade",
		"Have a Healthy Relationship",
		"Pull out a Loose Tooth",
		"Be an Attractive Woman",
		"Skip Class",
		"Tell if You Have Hit Puberty (Boys)",
		"Be Irresistible to Women",
		"Be Popular in Middle School (for Girls)",
		"Lose Weight Quickly and Safely (for Teen Girls)",
		"Talk to Girls as a Teen Boy",
		"Think of Stuff to Talk About with Your Boyfriend",
		"Cure Hiccups",
		"Control Your Dreams",
		"Get Kissable Lips",
		"Be a Gentleman",
		"Fake Vomit",
		"Look Cute and Dress Nicely for Middle School (Girls)",
		"Play Softball",
		"Talk to Your Crush Without Being Crushed",
		"Make a Man Fall in Love with You",
		"Play Yu Gi Oh!",
		"Take a Shower",
		"Be a Popular Girl",
		"Relax",
		"Treat a Scorpio",
		"Be a Good Boyfriend in Middle School",
		"Do a Split",
		"Cry On the Spot",
		"Deal With Impossible People",
		"Get a Guy to Always Want to Talk to You",
		"Stop Premature Ejaculation",
		"Stop Biting Your Nails",
		"Look Drop Dead Gorgeous",
		"Pull an All Nighter",
		"Know if He's Really Into You",
		"Treat a Foot Blister",
		"Be a Scene Queen",
		"Be a Spy",
		"Hint for a Kiss from a Guy",
		"Know if Your Girlfriend Is Cheating on You",
		"Tell a Boy You Like Him",
		"Be Cute",
		"Sing",
		"Fold Paper Into a Secret Note Square",
		"Text Message Someone You Like",
		"Get Your Homework Done Fast",
		"Dye Hair With Kool Aid",
		"Get Started in Parkour or Free Running",
		"Make a Cootie Catcher",
		"Run Faster",
		"Tell if a Cat is Pregnant",
		"Pass Time",
		"Pull an All Nighter in Your Room Alone (Kids)",
		"Start a Conversation When You Have Nothing to Talk About",
		"Clear Your Browser's Cache",
		"Look Beautiful As a Teenage Girl",
		"Look Like Victoria Justice",
		"Pass Your Driving Test",
		"Sleep Better",
		"Style Scene Hair",
		"Keep a Phone Conversation Going with Your Girlfriend",
		"Lose Weight As a Kid",
		"Crack a \"Master Lock\" Combination Lock",
		"Have Flawless Skin in a Week",
		"Tell That Your Crush Likes You Back",
		"Use Instagram",
		"Forget About a Girl You Love Who Has a Boyfriend",
		"Get a Guy to Like You in Seventh Grade",
		"Use a Tampon",
		"Kiss Passionately",
		"Calm Down",
		"Stop Laughing When You Laugh at Inappropriate Times",
		"Know if You Love Someone",
		"Make Small Breasts Look Bigger",
		"Turn a Guy on Through Text Message",
		"Clean Your Room Quickly and Efficiently",
		"Shave Your Bikini Area Completely",
		"Do a Backflip",
		"Drop Hints to a Girl That You Like Her",
		"Whistle With Your Fingers",
		"Improve Your Posture",
		"Come Up with Good Conversation Topics",
		"Get Ready for a Middle School Dance",
		"Make Newspaper Nails",
		"Stop Crying when You Are Very Upset",
		"Recognize a Manipulative or Controlling Relationship",
		"Turn On Your Boyfriend",
		"Be Cool",
		"Know when You Love A Guy",
		"Prepare for a Track Meet",
		"Tone Your Butt Fast",
		"Run a Fast Mile",
		"Hard Boil an Egg",
		"Be a Great Best Friend",
		"Be a Hipster",
		"Be Smooth with the Ladies",
		"Remove a Hickey",
		"Get Your Crush (for Boys and Girls)",
		"Look Cute in Front of Your Ex, Crush, or Boyfriend (Teen Girls Only)",
		"Make a Resume",
		"Act and Look Innocent (for Girls)",
		"Cheat On a Test",
		"Rapidly Learn to Play the Acoustic Guitar Yourself",
		"Treat a Woman",
		"Get Rid of Bruises",
		"Make Pictures Using Keyboard Keys",
		"Tell if Gold Is Real",
		"Calculate the Area of a Circle",
		"Get a Boy in Elementary School",
		"Get That Guy to Fall for You",
		"Hide an Erection",
		"Look Good In Your School Uniform",
		"Shave Your Genitals (Male)",
		"Talk to Your Crush if He Knows You Like Him",
		"Turn Your Partner On",
		"Be a Wizard",
		"Get a Girl to Fall for You",
		"Host a Sleepover (Teen Girls)",
		"Keep Your Girlfriend Happy",
		"Ask Out a Girl at School",
		"Get a Girl to Like You when She Likes Someone Else",
		"Post Ads to Craigslist",
		"Stop Vomiting",
		"Be a Singer",
		"Catch Mewtwo in PokÃ©mon FireRed/LeafGreen",
		"Drive Smoothly with a Manual Transmission",
		"Be Organized in School",
		"Be Popular in Elementary School",
		"Be a Country Girl",
		"Buy a Used Car from a Private Party",
		"Woo a Girl",
		"Be Less Perverted",
		"Fold a Dollar Bill to Make a Finger Ring",
		"Get Your Ex Back",
		"Find Things to Do in a Boring Class",
		"Pierce Your Ear",
		"Prepare a Relaxing Bath",
		"Treat a Virgo",
		"Get Good Grades",
		"Turn a Girl On",
		"Look Naturally Beautiful",
		"Make Money Fast",
		"Make Your Cell Phone Battery Last Longer",
		"Remove a Splinter",
		"Treat a Sunburn",
		"Cure Stomach Cramps",
		"Feel Better when You Have a Cold (for Girls)",
		"Find Out if Your Ex Still Likes You",
		"Have a Great Conversation",
		"Stop Being Jealous",
		"Tell a Girl You Love Her (Teenagers)",
		"Be Emo in Middle School",
		"Get Rid of Razor Bumps in the Bikini Area",
		"Make a Bow and Arrow",
		"Make Origami Paper Claws",
		"Skip School",
		"Get Skinnier Legs",
		"Get Straight \"A\"s",
		"Love Your Girlfriend",
		"Make a Shirt out of a One Dollar Bill",
		"Approach a Girl in Public",
		"Curl Hair",
		"Entertain Kids when You Are Babysitting",
		"Get Him to Make a Move",
		"Get the Biggoron's Sword in the Legend of Zelda, Ocarina of Time",
		"Grow Long Hair As a Guy",
		"Irish Dance",
		"Talk to Your Crush Even Though You Are Shy",
		"Tell if a Diamond is Real",
		"Be Really Sexy with Your Boyfriend",
		"Complete Club Penguin Secret Agent Missions",
		"Get Rid of a Pimple",
		"Grow Taller",
		"Act Like a Modern/Common Vampire",
		"Be Nice",
		"Make a Paper Boat",
		"Scrunch Hair",
		"Become a WWE Superstar",
		"Get a Man to Marry You",
		"Know if a Guy Is Cheating on You",
		"Overcome a Fear of Sex",
		"Pack For a Sleepover",
		"Tell Your Crush You Like Them",
		"Ace a Test",
		"Build a Yugioh Deck That Suits You",
		"Get Your Crush to Notice You in a Good Way (for Girls)",
		"Wash Your Hair",
		"Flirt Through IM",
		"Make a Guy Jealous",
		"Remove a Tattoo",
		"Text a Guy You Like",
		"Be a Cool Girl in Fifth Grade",
		"Come Out As a Gay or Lesbian Teen",
		"Cure Nausea",
		"Flirt In Sixth Grade",
		"Gain Control of Your Emotions",
		"Get a Guy to Like You in 10 Days (4Th 7Th Grade Girls)",
		"Get Ready for School in 20 Minutes (Teen Girls)",
		"Make Fake Vomit",
		"Make Pizza Dough",
		"Be a Spy Kid",
		"Convince Your Parents to Let You Get a Facebook Account",
		"Get a Teacher to Like You",
		"Get More Intimate Without Having Sex",
		"Kiss a Girl Smoothly with No Chance of Rejection",
		"Make Awesome Rubik's Cube Patterns",
		"Be Nice to People",
		"Get Rid of Dandruff (Natural Methods)",
		"Grow Your Fingernails",
		"Stop Swearing",
		"Dress and Be Like Rocky Blue",
		"Look Great (Girls)",
		"Recover after Wisdom Teeth Surgery",
		"Make a Friendship Bracelet",
		"Turn a Girl Friend Into a Girlfriend",
		"Apply Makeup",
		"Ignore People You No Longer Wish to Be Around",
		"Make a Movie",
		"Be Classy",
		"Become Famous",
		"Do a Cartwheel",
		"Get a Shadow Chao and a Sonic Chao",
		"Hug a Girl",
		"Know when Your Boyfriend Wants You to Kiss Him",
		"Sing High Notes",
		"Sleep When You Are Not Tired",
		"Slow Dance",
		"Stop Being Needy",
		"Ask a Girl to a Dance",
		"Care for Your Pet Rock",
		"Start a Friends With Benefits Relationship",
		"Unlock All Characters in Mario Kart Wii",
		"Write Song Lyrics",
		"Ask a Best Friend if They Like You",
		"Avoid Being Scared at Night",
		"Be the Girl All The Guys Want",
		"Become a Vegetarian",
		"Cuddle",
		"Get a Free Internet Connection",
		"Make a Guy Feel Sorry",
		"Make Someone Fall in Love with You",
		"Treat a Girl Well",
		"Become a Famous Singer",
		"Choose What Color to Wear",
		"Get a Boyfriend in Fifth Grade",
		"Get a Good Tan Without Getting Sunburned",
		"Get Clear, Smooth Skin",
		"Show a Girl You Like Her",
		"Be Cool (Teen Girls)",
		"Be Yourself",
		"Build a Shed",
		"Get a Guy in Your Teenage Years",
		"Make a Website",
		"Be in a Relationship Without Your Parents Knowing",
		"Know if You Are Ready to Have Sex",
		"Make a Guy That Used to Like You Like You Again",
		"Use a Bidet",
		"Convince Your Parents to Get You an iPhone",
		"Convince Your Parents to Let You Do Anything",
		"Get More Followers on Twitter",
		"Get People to Like You",
		"Get Rid of a Stuffy Nose Quickly",
		"Overcome Your Fear of Roller Coasters",
		"Read a Measuring Tape",
		"Shave Your Legs",
		"Feel Good About Yourself",
		"Get Bigger Chest Muscles (Pecs)",
		"Get Pregnant",
		"Look Good in Pictures",
		"Not Lose Your Girlfriend",
		"Understand a Cheating Girlfriend",
		"Get Rid of a Sore Neck",
		"Get Your Mom to Forgive You After You Do Something Stupid",
		"Gleek",
		"Kiss in a Variety of Ways",
		"Kiss With Braces",
		"Live Life to the Fullest",
		"Snuggle",
		"Wake Up Early",
		"Complete All the Treasure Rumors on Endless Ocean Blue World",
		"Grow Long Hair if You Are a Black Female",
		"Have Great Hair",
		"Run Without Getting Tired",
		"Tell a Girl You Like Her (Teen)",
		"Write Rap Lyrics",
		"Be a Better Person",
		"Find Lost Objects",
		"Grow an Apple Tree from a Seed",
		"Make a Braided Duct Tape Bracelet",
		"Make Dandelion Wine",
		"Overcome Shyness with Girls",
		"Show Your Girlfriend How Much You Care (for Guys)",
		"Become Sexy (for Boys Only)",
		"Cheat a Polygraph Test (Lie Detector)",
		"Get a Girl in 5th Grade in Public School",
		"Get a Girl Way out of Your League",
		"Get a Guy to Admit That He Likes You",
		"Have a Beauty Session for Pre Teen Girls (Ages Ten Through Twelve)",
		"Reduce Menstrual Cramps",
		"Tune a Guitar",
		"Win a Street Fight",
		"Be Happy",
		"Know if You are Pregnant",
		"Make Your Butt Bigger",
		"Take Flattering Photos of Yourself",
		"Treat a Cold",
		"Wear Your Converse",
		"Be Like Katniss Everdeen from the Hunger Games",
		"Choose Between Two Guys",
		"Get Rid of a Runny Nose",
		"Get Rid of Cramps ( for Girls)",
		"Kiss a Girl at the Movies"
	);

	/*
	* Injects checkmark html into $sections variable returned from MobileBasicArticleBuilder::parseNonMobileArticle
	*/
	public static function injectCheckMarksIntoSteps(&$sections) {
		// Add checkbox, and move the step_num div as a child
		$checkbox = '<div class="step_checkbox"><div class="step_num">\2</div></div>';
		$sections['steps']['html'] = preg_replace('@<li([^<]*)><div class="step_content"><div class="step_num">([^<]+)</div>@', 
			'<li\1>' . $checkbox . '<div class="step_content">', $sections['steps']['html']);
	}

	public static function getCheckMarksHtml() {
		EasyTemplate::set_path(dirname(__FILE__));
		$vars['json'] = self::getJSON();
		return EasyTemplate::html('checkmarks.tmpl.php', $vars);
	}

	public static function getStepsMsgs($num = 20) {
		return self::getRandomMsgs(self::$stepsMsgs, $num);
	}

	public static function getLastStepMsg() {
		return self::getRandomMsgs(self::$lastStepMsgs, 1);
	}

	public static function getRandomMsgs(&$msgs, $num = 20) {
		shuffle($msgs);
		$randMsgs = array();
		for ($i = 0; $i < $num; $i++) {
			$randMsgs[] = $msgs[$i];
		}
		return $randMsgs;
	}

	public static function getNextUrl() {
		global $wgTitle;
		$titles = self::$titles;
		shuffle($titles);
		$i = 0;
		// Don't select the title of the current article
		do {
			$title = $titles[$i++];
		} while ($i < sizeof($titles) - 1 || $title == $wgTitle->getText());
		$t = Title::newFromText($titles[0]);
		$url = "";
		if ($t && $t->exists()) {
			$url = $t->getLocalUrl();
		}
		return $url;
	}

	public static function getJSON() {
		return json_encode(array( 
			'msgs' => self::getStepsMsgs(), 
			'last' => self::getLastStepMsg(),
			'nextUrl' => self::getNextUrl()));
	}

/*
	// Modified Knuth algorithm to efficiently grab unique random numbers
	private static function getRandomMsgs(&$msgs, $num = 20) {
		$mSize = sizeof($msgs);
		$randMsgs = array();
		$im = 0;

		for ($in = 0; $in < $mSize && $im < $num; ++$in) {
			$rn = $mSize - $in;
			$rm = $num - $im;
			if (mt_rand(0, $mSize - 1) % $rn < $rm) {
				$randMsgs[] = $msgs[$in];
				$im++;
			}
		}
		return $randMsgs;
	}
*/
}

